Translated "Dosage of CPA"
tfsci-sc/articles pull request #4
Opened 2022-03-02 15:56 UTC by Bersella-AI

我尽力了。两段引用自其它文献的叙述使用了“trans women”或“transgender women”的称谓，在此予以保留。:heart:

2022-03-03 03:26 UTC, yucandy requested changes
感谢贡献qvq 可以麻烦你再看一下这两个小地方嘛？

2022-03-03 03:26 UTC, yucandy commented on cpa-dosage.md
> +# 在女性倾向跨性别者中，低剂量的醋酸环丙孕酮足以最大程度抑制睾酮
你觉得“低剂量的醋酸患病孕酮足以在女性倾向跨性别者中最大限度地抑制睾酮”作为标题会听起来更好些嘛？

2022-03-03 03:26 UTC, yucandy commented on cpa-dosage.md
> +像 CPA 一类的孕激素，可以显著抑制出生指派性别为男、未去势的人群当中的睾酮水平。从 1970 年代到 1980 年代初发表的一系列规模较小、质量较低的研究项目发现，健康年轻男性每日服用 5\~10 mg 的 CPA，可将睾酮水平抑制 40\~70%。其中，一些项目报告了使用 5 mg/天剂量的睾酮抑制程度，和使用 10 mg/天剂量的几乎一致（皆抑制了约 50%；[图表](https://c
未去势->性腺完整

2022-03-03 15:13 UTC, Bersella-AI commented on cpa-dosage.md
> +# 在女性倾向跨性别者中，低剂量的醋酸环丙孕酮足以最大程度抑制睾酮
已更正。此标题在中文语境下仍不大通顺易懂，遂略为优化：“低剂量的醋酸环丙孕酮足以最大限度地抑制女性倾向跨性别者的睾酮水平”。

2022-03-03 15:13 UTC, Bersella-AI commented on cpa-dosage.md
> +像 CPA 一类的孕激素，可以显著抑制出生指派性别为男、未去势的人群当中的睾酮水平。从 1970 年代到 1980 年代初发表的一系列规模较小、质量较低的研究项目发现，健康年轻男性每日服用 5\~10 mg 的 CPA，可将睾酮水平抑制 40\~70%。其中，一些项目报告了使用 5 mg/天剂量的睾酮抑制程度，和使用 10 mg/天剂量的几乎一致（皆抑制了约 50%；[图表](https://c
已更正。

2022-03-04 00:46 UTC, merged

2022-03-04 00:47 UTC, yucandy commented
感谢qwq